### ISSUE TITLE
PHP Issues

### ISSUE THREAD

**Issue by ghost** [splitbrains/parsoalto#10]
Hey! Looking to be able to use this, but it does not seem to be working properly. Any clue? Thank you much

``PHP Warning:  SimpleXMLElement::__construct(): /home/jvashey/parsoalto/configs/foo-bar.address.20250101.xml:485: parser error : Opening and ending tag mismatch: link-tate line 485 and link-state in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct(): /home/jvashey/parsoalto/configs/foo-bar.address.20250101.xml:485: parser error : Opening and ending tag mismatch: link-tate line 485 and link-state in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Warning:  SimpleXMLElement::__construct():               <link-tate>auto</link-state> in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct():               <link-tate>auto</link-state> in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Warning:  SimpleXMLElement::__construct():                                           ^ in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct():                                           ^ in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Warning:  SimpleXMLElement::__construct(): /home/jvashey/parsoalto/configs/foo-bar.address.20250101.xml:505: parser error : Opening and ending tag mismatch: slayer3 line 487 and layer3 in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct(): /home/jvashey/parsoalto/configs/foo-bar.address.20250101.xml:505: parser error : Opening and ending tag mismatch: slayer3 line 487 and layer3 in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Warning:  SimpleXMLElement::__construct():               </layer3> in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct():               </layer3> in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Warning:  SimpleXMLElement::__construct():                        ^ in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Warning: SimpleXMLElement::__construct():                        ^ in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
PHP Fatal error:  Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/jvashey/parsoalto/src/PaloAlto/File.php:84
Stack trace:
#0 /home/jvashey/parsoalto/src/PaloAlto/File.php(84): SimpleXMLElement->__construct('/home/jvashey/p...', 10240, true)
#1 /home/jvashey/parsoalto/src/PaloAlto/File.php(111): PaloAlto\File::createFromType('address', '/home/jvashey/p...')
#2 /home/jvashey/parsoalto/run.php(55): PaloAlto\File::createAndParse('/home/jvashey/p...')
#3 {main}
  thrown in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84

Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/jvashey/parsoalto/src/PaloAlto/File.php:84
Stack trace:
#0 /home/jvashey/parsoalto/src/PaloAlto/File.php(84): SimpleXMLElement->__construct('/home/jvashey/p...', 10240, true)
#1 /home/jvashey/parsoalto/src/PaloAlto/File.php(111): PaloAlto\File::createFromType('address', '/home/jvashey/p...')
#2 /home/jvashey/parsoalto/run.php(55): PaloAlto\File::createAndParse('/home/jvashey/p...')
#3 {main}
  thrown in /home/jvashey/parsoalto/src/PaloAlto/File.php on line 84
``

**Comment by olafhartong** [comment]
Which php version are you using? I've created this 4 years ago so it might be possible that the newer versions aren't compatible.
